services:
  db:
    image: postgres:17.2
    container_name: heuristicDB
    environment:
      POSTGRES_DB: heuristicDB
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U admin -d heuristicDB"]
      interval: 5s
      timeout: 3s
      retries: 20

  backend:
    build: ./backend/module/Reseking
    container_name: reseking-back
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/heuristicDB
      SPRING_DATASOURCE_USERNAME: admin
      SPRING_DATASOURCE_PASSWORD: admin123
    depends_on:
      db:
        condition: service_healthy

  frontend:
    build: ./frontend/Reseking
    container_name: reseking-front
    ports:
      - "3000:80"
    depends_on:
      - backend
